name: pymolenv
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310he2412df_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - biopython=1.79=py310he2412df_1
  - blas=1.0=mkl
  - bleach=5.0.0=pyhd8ed1ab_0
  - boost=1.74.0=py310hc781a3c_5
  - boost-cpp=1.74.0=h9f4b32c_8
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.5.18.1=h5b45459_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h0ac17fb_1011
  - certifi=2022.5.18.1=py310h5588dad_0
  - cffi=1.15.0=py310hcbf9ad4_0
  - cftime=1.6.0=py310h2873277_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - curl=7.83.1=h789b8ee_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.0=py310h8a704f9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h39d44d4_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hce3cb01_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py310he2412df_0
  - freetype=2.10.4=h546665d_1
  - gettext=0.19.8.1=ha2e2712_1008
  - greenlet=1.1.2=py310h8a704f9_2
  - griddataformats=1.0.1=pyhd8ed1ab_0
  - gsd=2.5.2=py310h2873277_0
  - gst-plugins-base=1.20.2=he07aa86_1
  - gstreamer=1.20.2=hdff456e_1
  - h5py=3.6.0=nompi_py310h00cbb18_100
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.12.1=nompi_h2a0e4a3_104
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=70.1=h0e60522_0
  - importlib-metadata=4.11.4=py310h5588dad_0
  - importlib_resources=5.7.1=pyhd8ed1ab_1
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.9.1=py310haa95532_0
  - ipython=8.4.0=py310h5588dad_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - jedi=0.18.1=py310h5588dad_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_1
  - jsonschema=4.6.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py310h5588dad_7
  - jupyter_client=7.3.1=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py310h5588dad_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - kiwisolver=1.4.2=py310h476a331_1
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libclang=14.0.4=default_h77d9078_0
  - libclang13=14.0.4=default_h77d9078_0
  - libcurl=7.83.1=h789b8ee_0
  - libdeflate=1.10=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.70.2=h3be07f2_4
  - libiconv=1.16=he774522_0
  - libnetcdf=4.8.1=nompi_h1cc8e9d_102
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libssh2=1.10.0=h680486a_2
  - libtiff=4.3.0=hc4061b1_4
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.9.14=hf5bbc77_0
  - libzip=1.8.0=hfed4ece_1
  - libzlib=1.2.12=h8ffe710_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py310he2412df_1
  - matplotlib-base=3.5.2=py310h79a7439_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mdanalysis=2.2.0=py310hf5e1058_0
  - mistune=0.8.4=py310he2412df_1005
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - mmtf-python=1.1.2=py_0
  - mrcfile=1.3.0=pyh44b312d_0
  - msgpack-python=1.0.4=py310h476a331_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nb_conda_kernels=2.3.1=py310haa95532_0
  - nbclient=0.6.4=pyhd8ed1ab_1
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - netcdf4=1.5.8=nompi_py310h5489b47_101
  - networkx=2.8.3=pyhd8ed1ab_0
  - notebook=6.4.11=pyha770c72_0
  - numpy=1.22.3=py310h6d2d95c_0
  - numpy-base=1.22.3=py310h206c741_0
  - openbabel=3.1.1=py310h925f80e_3
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1o=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py310hf5e1058_2
  - pandoc=2.18=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py310h767b3fd_0
  - pip=22.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - prolif=1.0.0=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - prompt_toolkit=3.0.29=hd8ed1ab_0
  - psutil=5.9.1=py310he2412df_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py3dmol=1.8.0=pyhd8ed1ab_0
  - pycairo=1.21.0=py310h3255e4b_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.4=py310hbabf5d4_1
  - pyqt5-sip=12.9.0=py310h8a704f9_1
  - pyrsistent=0.18.1=py310he2412df_1
  - python=3.10.4=h9a09f29_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pywin32=303=py310he2412df_0
  - pywinpty=2.0.5=py310h00ffb61_1
  - pyzmq=23.1.0=py310h73ada01_0
  - qt-main=5.15.3=h467ea89_2
  - qtconsole=5.3.0=pyhd8ed1ab_0
  - qtconsole-base=5.3.0=pyha770c72_0
  - qtpy=2.1.0=pyhd8ed1ab_0
  - rdkit=2022.03.3=py310hc4884e0_0
  - reportlab=3.5.68=py310h0e7cf82_1
  - scikit-learn=1.0.2=py310h4ed8f06_0
  - scipy=1.7.3=py310h6d2d95c_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.3.2=py310h5588dad_0
  - sip=6.5.1=py310h8a704f9_2
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlalchemy=1.4.37=py310he2412df_0
  - sqlite=3.38.5=h8ffe710_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - statsmodels=0.13.2=py310h2873277_0
  - terminado=0.15.0=py310h5588dad_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tidynamics=1.0.0=py_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py310he2412df_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.2.2.post1=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - unicodedata2=14.0.0=py310he2412df_1
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.0=py310h5588dad_0
  - winpty=0.4.3=4
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h8ffe710_0
  - zstd=1.5.2=h6255e5f_1
prefix: C:\Users\renlab\anaconda3\envs\pymolenv
